In [3]:
import psycopg2
import pandas
from sqlalchemy import create_engine
from bokeh.plotting import figure, output_file, show
from bokeh.tile_providers import CARTODBPOSITRON, get_provider

In [26]:
alchemyEngine = create_engine('postgresql+psycopg2://etl:etl@localhost/db', pool_recycle=3600);
connection = alchemyEngine.connect();
   
# Get the date of the last temperature loaded
sql = """select * from temperature_level ;
"""
#data = pandas.read_sql(sql, connection)
data = pandas.read_sql_query(sql,con=connection)

# Close database connection
connection.close()

In [27]:
data

,region,country,city,quarter,avgtemp,templevel
0,Africa,Algeria,Algiers,1,11.89,Medium
1,Africa,Algeria,Algiers,2,19.12,High
2,Africa,Algeria,Algiers,3,25.28,Very High
3,Africa,Algeria,Algiers,4,15.72,Medium
4,Africa,Benin,Cotonou,1,28.60,Very High
...,...,...,...,...,...,...
1279,South/Central America & Carribean,Uruguay,Montvideo,4,18.38,High
1280,South/Central America & Carribean,Venezuela,Caracas,1,26.13,Very High
1281,South/Central America & Carribean,Venezuela,Caracas,2,27.44,Very High
1282,South/Central America & Carribean,Venezuela,Caracas,3,28.13,Very High
1283,South/Central America & Carribean,Venezuela,Caracas,4,27.49,Very High

In [30]:
from datetime import date
from random import randint

from bokeh.io import show
from bokeh.models import ColumnDataSource, DataTable, DateFormatter, TableColumn

source = ColumnDataSource(data)

columns = [
        TableColumn(field="region", title="Region"),
        TableColumn(field="country", title="Country"),
        TableColumn(field="city", title="City"),
        TableColumn(field="quarter", title="Quarter"),
        TableColumn(field="avgtemp", title="Temperature"),
        TableColumn(field="templevel", title="Temperature Level"),
    ]
data_table = DataTable(source=source, columns=columns, width=800, height=800)

#output_file("pages/result.html")
show(data_table)